version: '2'

services:

  web-server:
    container_name: web-server
    image: 'web-server'
    build:
      context: ./docker/nginx
    ports:
      - ${NGINX_PORT}:80
    restart: unless-stopped
    depends_on:
      - php-fpm
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/company-management

  php-fpm:
    container_name: php-srv
    image: php-srv
    build:
      context: ./docker/php
    ports:
      - ${PHP_PORT}:9000
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www/html/company-management

  db:
    container_name: main-sql
    image: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/mysql/my.conf:/etc/mysql/conf.d/my.cnf
      - main:/var/lib/mysql

volumes:
  main:
