<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateManagerRequest;
use App\Models\Branch;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Illuminate\View\View;
use Yajra\DataTables\DataTables;

class ManagerController extends Controller
{
    public function index(): JsonResponse|View
    {
        if(request()->ajax()){
            $data = User::managers()
                ->latest()
                ->get();

            return DataTables::of($data)
                ->addColumn('name', function($row) {
                    return $row->full_name ;
                })
                ->addColumn('branch', function($row) {
                    return $row->branch->name ?? 'N/A';
                })
                ->addColumn('action', function($row){
                    $actionBtn = '<a href="javascript:void(0)" class="edit btn btn-success btn-sm">Edit</a> <a href="javascript:void(0)" class="delete btn btn-danger btn-sm">Delete</a>';
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make();
        }

        return view('managers.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $data['branches'] = Branch::select(['id','name'])
            ->where('organization_id',auth()->user()->branch->organization_id)
            ->get();

        return view('managers.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CreateManagerRequest $request)
    {
        $autoGeneratedPassword = Str::random(8);

        $user = User::create([
            ...$request->validated(),
            'password' => Hash::make($autoGeneratedPassword)
        ]);

        $user->assignRole(data_get(config('permissions'), "manager.name"));

        return redirect()->route('managers.index')->with('success','Created Manager');
    }

    /**
     * Display the specified resource.
     */
    public function show(User $manager)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $manager)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $manager)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $manager)
    {
        //
    }
}
